docs(core): readme changes for passing xml with the sourceloop-workflow web component
sourcefuse/workflows-creator pull request #28
Opened 2023-09-06 07:13 UTC by arpit1503khanna

GH-25

## Description
Changes were made in the readme to illustrate how bpmn diagram value can be passed with the web component. In VanillaJS if the value bpmn diagram needs to be passed it can be done like given below. In the value of the diagram, XML of the workflow needs to be passed and it will render the desired workflow.

element.setAttribute("diagram", " ")

Fixes #25 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-06 10:43 UTC, yeshamavani commented
rectify the commit message.

2023-09-06 10:45 UTC, yeshamavani requested changes
commit message needs to be rectified

2023-09-06 10:45 UTC, yeshamavani commented on projects/workflows-creator/README.md
> +NOTE: If `envIdentifier` is required it must be provided in the global `window` object as shown below, otherwise it will be rendered as undefined. This step is needed only in non-angular applications
specify that diagram attribute needs to be set 
justifying your added piece of code in example below

2023-09-15 10:11 UTC, yeshamavani commented
@arpit1503khanna  is this resolved

2023-09-15 14:18 UTC, arpit1503khanna commented
> @arpit1503khanna is this resolved

I have asked aryansh sir , to let me know if the solution recommended is working or not.

2023-09-18 12:30 UTC, closed without merging