fix(ci-cd): setup the release process
sourcefuse/workflows-creator pull request #4
Opened 2023-03-02 10:25 UTC by yeshamavani

GH-2

## Description

setup the release process

Fixes #2

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-07 06:24 UTC, akshatdubeysf requested changes

2023-03-07 06:24 UTC, akshatdubeysf commented on LICENSE
> +Copyright (c) [2021] [SourceFuse]
2023

2023-03-09 06:31 UTC, yeshamavani commented on LICENSE
> +Copyright (c) [2021] [SourceFuse]
done

2023-03-09 07:02 UTC, merged

2023-03-09 07:14 UTC, sfdevops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sourceloop/workflows-creator/v/1.0.0)
- [GitHub release](https://github.com/sourcefuse/workflows-creator/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: